language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.5
    - os: osx
      language: generic
      env: PYTHON_VER=3.6

    - os: linux
      python: 3.5
      env: PYTHON_VER=3.5
    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

install:
  - ./.travis/install.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - # Useful for debugging any issues with conda
  - conda info -a

    # Create test environment for package
  - conda create -n test python=$PYTHON_VER pip pytest pytest-cov
  - conda activate test

    # Install pip only modules
  - pip install codecov

    # Build and install package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --use-local che696_examples


script:
  - pytest -v --cov=che696_examples che696_examples/tests/

notifications:
    email: false

after_success:
  - codecov
